### ISSUE TITLE
Skip brush deletes adjacent faces on neighbor brushes

### ISSUE THREAD

**Issue by degradka** [jitspoe/godot_bsp_importer#14]
I've tried to use skip brush as a clip brush and found that for some reason it skips brushes on neighbor brushes. Maybe that's not an issue at all, and I'm just stupid, but it seems like an issue to me :)

I'm using `ericw-tools qbsp v2.0.0-alpha3` with a custom game set up in Trenchbroom.
My qbsp flags are: `-noextendedsurfflags -nolog -subdivide 0`

The map and bsp files to reproduce the issue: [dev_level.zip](https://github.com/jitspoe/godot_bsp_importer/files/13489792/dev_level.zip)

<details><summary>Screenshots</summary>

Trenchbroom:
![trenchbroom](https://github.com/jitspoe/godot_bsp_importer/assets/69397649/90007a15-b3b6-4411-902d-f740322c3657)

Editor:
![editor](https://github.com/jitspoe/godot_bsp_importer/assets/69397649/cebd8378-5f1b-4216-a671-619c9484e62d)

Game:
![game](https://github.com/jitspoe/godot_bsp_importer/assets/69397649/929136bb-5ca0-4686-b2b9-6580e077538a)

</details>

**Comment by jitspoe** [comment]
Yeah, the way the QBSP CSG stuff is set up, that is going to happen.  There are 2 ways you can work around this:
1) Make the brush slightly smaller so it doesn't contact any other brushes.
2) Make the brush some sort of brush entity (like a func_wall), then use the entity remap to map to a scene with just a static body.
