### ISSUE TITLE
Incorrect generation of collision for custom entities

### ISSUE THREAD

**Issue by degradka** [jitspoe/godot_bsp_importer#15]
I made a custom entity called func_door and added it to game's fgd: `@SolidClass = func_door : "Basic Door" []`
In Trenchbroom everything looks good:
<details><summary>TB Screenshot</summary>

![image](https://github.com/jitspoe/godot_bsp_importer/assets/69397649/b88c70ac-1eda-4e94-bb5d-4c34f638e2c9)

</details> 

In Godot, I remapped func_door entity to single `StaticBody3D` scene. Upon bsp import, again, everything looks good as well:
<details><summary>Scene Tree Screenshot</summary>

![image](https://github.com/jitspoe/godot_bsp_importer/assets/69397649/06c65589-7645-4166-b712-93ea7af7bb78)

</details> 

But if you look closely, the generated collision is shrunk by approx. 0.031 units related to all sides of the mesh:

<details><summary>Screenshot</summary>

![image](https://github.com/jitspoe/godot_bsp_importer/assets/69397649/705be2da-4ba0-4257-bc05-018c418c6604)

</details>

I'm using `ericw-tools qbsp v2.0.0-alpha3` with a custom game set up in Trenchbroom.
My qbsp flags are: `-noextendedsurfflags -nolog -subdivide 0`

The map and bsp files to reproduce [collisiongen_issue.zip](https://github.com/jitspoe/godot_bsp_importer/files/13490048/collisiongen_issue.zip)

**Comment by jitspoe** [comment]
Yeah, I just noticed that.  For some reason, the Quake tools shrink the collision by 1 unit.  I fixed it locally but didn't get around to putting it up on github yet.  Will fix soon.

**Comment by jitspoe** [comment]
Fixed: https://github.com/jitspoe/godot_bsp_importer/commit/9707fabdd6e3b976fed1fe2b9f805feab859cff1
