### ISSUE TITLE
Import process hangs on maps compiled with `-notex`

### ISSUE THREAD

**Issue by hemebond** [jitspoe/godot_bsp_importer#22]
Maps compiled using the ericw tools qbsp with the `-notex` parameter cause the import process to hang.

![image](https://github.com/user-attachments/assets/f4d3aed5-e47c-4c1f-be87-408f33cfa7b8)

Since most Godot games using Quake maps will be providing external files and materials anyway `-notex` is a good way to reduce file size by not including innecessary data.

**Comment by jitspoe** [comment]
Thanks for letting me know.  Currently the compiled-in textures are required to get the proper texture size for UV's.  It would be good to add support for external textures, though.

**Comment by hemebond** [comment]
I see. I thought the UV data was still included, just not the texture/image data.

**Comment by jitspoe** [comment]
I've updated the importer to handle bsp files without textures and grab the texture dimensions from external textures, along with automatically generating materials and a bunch of other stuff in e1a3cdd240202d665614268ba5f6499b6b4e8382

Hopefully this fixes your issue!  Might be a few days be fore the asset library is updated.
