### ISSUE TITLE
Setting non-zero 'origin' on an entity messes up worldspawn collision shapes

### ISSUE THREAD

**Issue by Skaruts** [jitspoe/godot_bsp_importer#8]
When you add the spawnarg `origin` with something other than `0 0 0` to an entity, the worldspawn collision shapes go crazy. The vertices go off to far away places, for some reason.

EDIT: seems like it's when you move the entity up, to positive Z (the 3rd value) that it causes problems. Placing the entity anywhere, but with `Z <= 0`, doesn't cause any problems.

![2023-10-06 17_21_18-bsp_test_01 bsp - BSP Test - Godot Engine](https://github.com/jitspoe/godot_bsp_importer/assets/6277234/ee43e613-167a-42c5-90cb-e0c4d168785f)

**Comment by Skaruts** [comment]
Seems to be something about the `BspClipper` script, called from `convert_planes_to_points` in `bsp_reader.gd`. `BspClipper.begin` defaults all the vertices to `TESTMAX`, and it's that value that most of the collision vertices have.

I just can't see how an entity's origin could affect the calculations of the worldspawn's collisions.

**Comment by jitspoe** [comment]
Interesting!  What entity are you setting the origin on?  I've done it with point entities (spawners and such), but setting it on the worldspawn or other brush entities could definitely cause undesired effects.  I hadn't tested that.

**Comment by Skaruts** [comment]
The one I'm using for testing is a point entity (a light). But this happens regardless of which entity I do it on.

And maybe this isn't related to the entities (I commented out the code in bsp_reader that creates the entity list, and the problem persisted). Just for some reason it goes away when I remove the entity in TB, or set the origin's height value to `<= 0`.

Also saw this happening in your video at 0:59: https://youtu.be/RvCyg_lm_7w?si=w1ULuC5Rec-UrUyN&t=59

I attached my project with my game definition.
[bsp_test_stuff.zip](https://github.com/jitspoe/godot_bsp_importer/files/12837374/bsp_test_stuff.zip)

I have four test maps there, I'm mostly using `nrc_bsp_test_03` and `bsp_test_04`. The `nrc_*` version was made in NetRadiant-custom, and there's no difference in the results.

I'm compiling the bsp files with just `qbsp -path <path to textures> <map_filename>`

**Comment by jitspoe** [comment]
Ok, seems the model mins and maxs are critical for some brushes.  In my use cases, they didn't appear to be so I kind of dropped that.  Fix in coming.

**Comment by jitspoe** [comment]
Fixed in https://github.com/jitspoe/godot_bsp_importer/commit/f0681e5cd4182763142cd4d51f1480dd492373f8

**Comment by Skaruts** [comment]
Thank you. 

The collisions aren't going wild anymore. But it kinda seems like there might still be an issue present, though. They're not conforming to the shapes of the original brushes. Is this supposed to happen?

###### (left = correct (no entities), right = incorrect)

![collisions](https://github.com/jitspoe/godot_bsp_importer/assets/6277234/e4c85e8b-8da5-4b47-b5cf-11ab21f0eed9)

**Comment by jitspoe** [comment]
The original brushes are not stored in Quake1BSP files.  That should effectively be the collision that's used in-game.
